### ISSUE TITLE
Glew windows downlaod source

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2-visualiser#102]
glew dependency dowloads for windows CI builds occasionally fails, moving to a gh-hosted source should be more stable than downloading from sourceforge (as if gh has issues, the actions will have issues anyway). 

It seems that there is now an official glew repository on github, based on a link and info on http://glew.sourceforge.net/

![image](https://user-images.githubusercontent.com/628937/186710033-4eaaa0cd-31cc-4b9a-b2de-7e70ad2998d6.png)

This has releases for 2.0.0, 2.1.0  and 2.2.0 which include the `glew-2.1.0-win32.zip` which should be the downlaod we need. Just changing the uri might work. 

`https://github.com/nigels-com/glew/releases/download/glew-2.1.0/glew-2.1.0-win32.zip`

**Comment by Robadob** [comment]
> Just changing the uri might work.

Would expect it to work, mirror should provide identical file structure. May hack a PR out later tonight.
