### ISSUE TITLE
Visualiser window icon fails to load

### ISSUE THREAD

**Issue by daniele-baccega** [FLAMEGPU/FLAMEGPU2-visualiser#125]
Hi,
I tried to run the cpp template (https://github.com/FLAMEGPU/FLAMEGPU2-model-template-cpp) with the visualization.
I compiled it using these commands:
_mkdir -p build && cd build
cmake .. -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_ARCHITECTURES=72 -DFLAMEGPU_VISUALISATION=ON
cmake --build . --target all -j 8_

When I run the command _./bin/Release/template_ I obtained this error:

**terminate called after throwing an instance of 'flamegpu::visualiser::ResourceError'
  what():  /home/daniele/Desktop/circles-flame-gpu-2/build/_deps/flamegpu_visualiser-src/src/flamegpu/visualiser/texture/Texture.cpp(327): Texture::loadImage(): File '/tmp/flamegpu/vis/17293405377044466258_flamegpu_icon.png' could not be loaded!
 DevIL_Image error: The extension of the specified filename was not correct for the type of image - loading function.
Aborted**

I don't know how to solve it, could you help me?

**Configuration:**
OS: Ubuntu 20.04.5 LTS
CUDA version: 11.4.315
GPU NVIDIA Tegra Xavier (nvgpu)/integrated

Thank you very much

**Comment by Robadob** [comment]
If you want to prevent this programmatically, here's the related code

This bit of code loads the icon and set's it for the window.

https://github.com/FLAMEGPU/FLAMEGPU2-visualiser/blob/02097b5ca1bf38a52693e926d0d750d972a2ae80/src/flamegpu/visualiser/Visualiser.cpp#L1215

This class represents the splash screen (would probably want to update lines 15 and 25)

https://github.com/FLAMEGPU/FLAMEGPU2-visualiser/blob/master/src/flamegpu/visualiser/ui/SplashScreen.cpp

**Comment by daniele-baccega** [comment]
Thank you very much

I'm sorry to bother you all the time, but now I have an other error and I don't know if it is caused by FLAMEGPU or not:

**X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Serial number of failed request:  188
  Current serial number in output stream:  188**

This happend when i run the simulation with the visualisation (_./bin/Release/template_).

Thank you again!

**Comment by Robadob** [comment]
Are you able to reproduce the error with a debug build via a debugger (probably `gdb`) to retrieve a backtrace (stack trace)?

`Xlib` is an OS window system library on Linux, so that's where the error is occurring. From that message alone, it's hard to see a clear cause. It's possible SDL2 (the library we use to provide the visualisation window) is passing a bad value to the OS to setup the window, but without a stack trace I can't really speculate further as FLAMEGPU2's involvement will be much lower down the call stack.


Based on the documentation for [`X_ChangeProperty()`](https://tronche.com/gui/x/xlib/window-information/XChangeProperty.html), it's the xlib method for setting window properties. Therefore, it's possible you've made a mistake when commenting out the icon code, and it's now trying to pass a null pointer/image as the window icon? (vague guess)

**Comment by daniele-baccega** [comment]
I tried to use gdb but, as you can see in the screenshot, there is no backtrace:
![gdb](https://user-images.githubusercontent.com/94167431/225573335-b5fc6c30-adbb-47df-a215-a9231eab80ca.png)

At the moment I did not modify the code, but I substitute the image that caused the previous error

**Comment by daniele-baccega** [comment]
I tried to use gdb but, as you can see in the screenshot, there is no backtrace:
![gdb](https://user-images.githubusercontent.com/94167431/225573335-b5fc6c30-adbb-47df-a215-a9231eab80ca.png)

At the moment I did not modify the code, but I substitute the image that caused the previous error

**Comment by Robadob** [comment]
I'm not a `gdb` expert (I primarily work on Windows), not sure if @ptheywood has anything to add.

**Comment by daniele-baccega** [comment]
Now I tried to modify the code commenting the body of the Visualiser::setWindowIcon function and modifying the SplashScreen.cpp in this way (removing all the code related to the logo):

**#include "flamegpu/visualiser/ui/SplashScreen.h"

#include <string>

#include "flamegpu/visualiser/ui/Sprite2D.h"
#include "flamegpu/visualiser/ui/Text.h"
#include "flamegpu/visualiser/util/fonts.h"

namespace flamegpu {
namespace visualiser {

SplashScreen::SplashScreen(const glm::vec3& textColor, const std::string& message, bool isPython)
    : text_offset(0) {
     text = std::make_shared<Text>("Loading...", 45, textColor, fonts::findFont({ "Arial" }, fonts::GenericFontFamily::SANS).c_str());
    // Calculate offsets for vertical stacking
    const int FULL_HEIGHT = text->getHeight();
    const int MID_HEIGHT = FULL_HEIGHT / 2;
    text_offset.y = MID_HEIGHT - (text->getHeight() / 2);
}
std::vector<SplashScreen::OverlayItem> SplashScreen::getOverlays() const {
    return std::vector<OverlayItem>{OverlayItem{ text, text_offset, 0 }};
}

}  // namespace visualiser
}  // namespace flamegpu**

Now when I run the _./bin/Release/templace_ it seems to run (as you can see in the screenshot), but it does not open the visualisation window. Did I modify the code correctly?

![screen](https://user-images.githubusercontent.com/94167431/225600088-355265fd-82d7-41c6-9467-2f80a1750c23.png)

**Comment by Robadob** [comment]
> Did I modify the code correctly?

Yes that's the same as the change I would have made.

> Now when I run the ./bin/Release/templace it seems to run (as you can see in the screenshot), but it does not open the visualisation window.

Now the error is gone, have you tried running it without GDB?

There's no reason to my knowledge the window shouldn't appear if you've only modified code related to the icon/splash screen.
