### ISSUE TITLE
Custom resource export caching relative paths

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2-visualiser#46]
When paths are used with `setModel()` rather than stock objects, they are cached to `TMPDIR`.

This uses the literatl path of the resource, but accepts relative paths, this can lead to the cahced files being outiside of their expected locations. 

I.e. if a resource path of `../resources/cylinder_geom.obj` is used, this will be cached at `/tmp/fgpu2/vis/../resources/cylinder_geom.obj.sdl_export`, outside of `/tmp/fgpu2/vis`. 

With enough `../` this could easily be a location which the user cannot write to, or shouldn't be able to write to.

**Comment by Robadob** [comment]
haha whoops, may address this tonight.
Sensible time for me to fix that sdl_export is cached to diff directory to shaders. (`visresources` vs `vis/resources`)
